[2023-11-09T02:53:41.437+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: early_sepsis_prediction.train_test_valid_files manual__2023-11-09T02:53:39.223803+00:00 [queued]>
[2023-11-09T02:53:41.445+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: early_sepsis_prediction.train_test_valid_files manual__2023-11-09T02:53:39.223803+00:00 [queued]>
[2023-11-09T02:53:41.446+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-09T02:53:41.446+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-11-09T02:53:41.447+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-09T02:53:41.458+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): train_test_valid_files> on 2023-11-09 02:53:39.223803+00:00
[2023-11-09T02:53:41.465+0000] {standard_task_runner.py:55} INFO - Started process 1382 to run task
[2023-11-09T02:53:41.470+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'early_sepsis_prediction', 'train_test_valid_files', 'manual__2023-11-09T02:53:39.223803+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp4izy4y2b']
[2023-11-09T02:53:41.471+0000] {standard_task_runner.py:83} INFO - Job 69: Subtask train_test_valid_files
[2023-11-09T02:53:41.546+0000] {task_command.py:388} INFO - Running <TaskInstance: early_sepsis_prediction.train_test_valid_files manual__2023-11-09T02:53:39.223803+00:00 [running]> on host 4460f47ac51f
[2023-11-09T02:53:41.619+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=early_sepsis_prediction
AIRFLOW_CTX_TASK_ID=train_test_valid_files
AIRFLOW_CTX_EXECUTION_DATE=2023-11-09T02:53:39.223803+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-09T02:53:39.223803+00:00
[2023-11-09T02:53:41.621+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/pylab.py", line 92, in train_test_valid_files
    new_path =os.path.join(os.path.dirname(__file__), '../data',train_files)
  File "/usr/local/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/local/lib/python3.7/genericpath.py", line 153, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'list'
[2023-11-09T02:53:41.635+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=early_sepsis_prediction, task_id=train_test_valid_files, execution_date=20231109T025339, start_date=20231109T025341, end_date=20231109T025341
[2023-11-09T02:53:41.645+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 69 for task train_test_valid_files (join() argument must be str or bytes, not 'list'; 1382)
[2023-11-09T02:53:41.682+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-11-09T02:53:41.712+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
