[2023-11-09T03:00:20.158+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Data_pipeline_dag.train_test_valid_split scheduled__2023-11-09T02:59:48.569875+00:00 [queued]>
[2023-11-09T03:00:20.169+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Data_pipeline_dag.train_test_valid_split scheduled__2023-11-09T02:59:48.569875+00:00 [queued]>
[2023-11-09T03:00:20.170+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-09T03:00:20.171+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-11-09T03:00:20.171+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-09T03:00:20.190+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): train_test_valid_split> on 2023-11-09 02:59:48.569875+00:00
[2023-11-09T03:00:20.197+0000] {standard_task_runner.py:55} INFO - Started process 1846 to run task
[2023-11-09T03:00:20.206+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Data_pipeline_dag', 'train_test_valid_split', 'scheduled__2023-11-09T02:59:48.569875+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmp_m6i3_by']
[2023-11-09T03:00:20.208+0000] {standard_task_runner.py:83} INFO - Job 86: Subtask train_test_valid_split
[2023-11-09T03:00:20.291+0000] {task_command.py:388} INFO - Running <TaskInstance: Data_pipeline_dag.train_test_valid_split scheduled__2023-11-09T02:59:48.569875+00:00 [running]> on host 4460f47ac51f
[2023-11-09T03:00:20.362+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Data_pipeline_dag
AIRFLOW_CTX_TASK_ID=train_test_valid_split
AIRFLOW_CTX_EXECUTION_DATE=2023-11-09T02:59:48.569875+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-09T02:59:48.569875+00:00
[2023-11-09T03:00:20.364+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/demo.py", line 24, in train_test_valid_files
    for f in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/../data/Dataset'
[2023-11-09T03:00:20.378+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=Data_pipeline_dag, task_id=train_test_valid_split, execution_date=20231109T025948, start_date=20231109T030020, end_date=20231109T030020
[2023-11-09T03:00:20.389+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 86 for task train_test_valid_split ([Errno 2] No such file or directory: '/opt/airflow/dags/../data/Dataset'; 1846)
[2023-11-09T03:00:20.416+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-11-09T03:00:20.442+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
