[2023-11-09T22:22:30.908+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: early_sepsis_prediction.feature_engineering manual__2023-11-09T22:22:25.528585+00:00 [queued]>
[2023-11-09T22:22:30.926+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: early_sepsis_prediction.feature_engineering manual__2023-11-09T22:22:25.528585+00:00 [queued]>
[2023-11-09T22:22:30.927+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-09T22:22:30.929+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-11-09T22:22:30.931+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-09T22:22:30.952+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): feature_engineering> on 2023-11-09 22:22:25.528585+00:00
[2023-11-09T22:22:30.968+0000] {standard_task_runner.py:55} INFO - Started process 3875 to run task
[2023-11-09T22:22:30.975+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'early_sepsis_prediction', 'feature_engineering', 'manual__2023-11-09T22:22:25.528585+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp_c0vp5nx']
[2023-11-09T22:22:30.981+0000] {standard_task_runner.py:83} INFO - Job 249: Subtask feature_engineering
[2023-11-09T22:22:31.092+0000] {task_command.py:388} INFO - Running <TaskInstance: early_sepsis_prediction.feature_engineering manual__2023-11-09T22:22:25.528585+00:00 [running]> on host 911414a99fc3
[2023-11-09T22:22:31.168+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Pavs
AIRFLOW_CTX_DAG_ID=early_sepsis_prediction
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2023-11-09T22:22:25.528585+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-09T22:22:25.528585+00:00
[2023-11-09T22:22:31.202+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/pylab1.py", line 83, in feature_engineering
    train_df = pickle.loads(train_data)
TypeError: a bytes-like object is required, not 'NoneType'
[2023-11-09T22:22:31.215+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=early_sepsis_prediction, task_id=feature_engineering, execution_date=20231109T222225, start_date=20231109T222230, end_date=20231109T222231
[2023-11-09T22:22:31.228+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 249 for task feature_engineering (a bytes-like object is required, not 'NoneType'; 3875)
[2023-11-09T22:22:31.270+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-11-09T22:22:31.301+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
