[2023-11-09T04:03:03.061+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: early_sepsis_prediction.preprocess_test_val_data manual__2023-11-09T04:02:57.303431+00:00 [queued]>
[2023-11-09T04:03:03.071+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: early_sepsis_prediction.preprocess_test_val_data manual__2023-11-09T04:02:57.303431+00:00 [queued]>
[2023-11-09T04:03:03.073+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-09T04:03:03.074+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-11-09T04:03:03.074+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-09T04:03:03.100+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): preprocess_test_val_data> on 2023-11-09 04:02:57.303431+00:00
[2023-11-09T04:03:03.109+0000] {standard_task_runner.py:55} INFO - Started process 6068 to run task
[2023-11-09T04:03:03.116+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'early_sepsis_prediction', 'preprocess_test_val_data', 'manual__2023-11-09T04:02:57.303431+00:00', '--job-id', '239', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp2s2m5o3c']
[2023-11-09T04:03:03.119+0000] {standard_task_runner.py:83} INFO - Job 239: Subtask preprocess_test_val_data
[2023-11-09T04:03:03.224+0000] {task_command.py:388} INFO - Running <TaskInstance: early_sepsis_prediction.preprocess_test_val_data manual__2023-11-09T04:02:57.303431+00:00 [running]> on host 4460f47ac51f
[2023-11-09T04:03:03.296+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=early_sepsis_prediction
AIRFLOW_CTX_TASK_ID=preprocess_test_val_data
AIRFLOW_CTX_EXECUTION_DATE=2023-11-09T04:02:57.303431+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-09T04:02:57.303431+00:00
[2023-11-09T04:03:03.298+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: preprocess_test_val_data() missing 4 required positional arguments: 'mean_values_data', 'std_values_data', 'valid_data', and 'test_data'
[2023-11-09T04:03:03.312+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=early_sepsis_prediction, task_id=preprocess_test_val_data, execution_date=20231109T040257, start_date=20231109T040303, end_date=20231109T040303
[2023-11-09T04:03:03.324+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 239 for task preprocess_test_val_data (preprocess_test_val_data() missing 4 required positional arguments: 'mean_values_data', 'std_values_data', 'valid_data', and 'test_data'; 6068)
[2023-11-09T04:03:03.369+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-11-09T04:03:03.391+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
