[2023-11-09T03:03:20.084+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Data_pipeline_dag.train_test_valid_split scheduled__2023-11-09T03:02:48.569875+00:00 [queued]>
[2023-11-09T03:03:20.094+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Data_pipeline_dag.train_test_valid_split scheduled__2023-11-09T03:02:48.569875+00:00 [queued]>
[2023-11-09T03:03:20.095+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-09T03:03:20.096+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-11-09T03:03:20.096+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-09T03:03:20.110+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): train_test_valid_split> on 2023-11-09 03:02:48.569875+00:00
[2023-11-09T03:03:20.116+0000] {standard_task_runner.py:55} INFO - Started process 2044 to run task
[2023-11-09T03:03:20.121+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Data_pipeline_dag', 'train_test_valid_split', 'scheduled__2023-11-09T03:02:48.569875+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmp7gi0oco3']
[2023-11-09T03:03:20.124+0000] {standard_task_runner.py:83} INFO - Job 92: Subtask train_test_valid_split
[2023-11-09T03:03:20.199+0000] {task_command.py:388} INFO - Running <TaskInstance: Data_pipeline_dag.train_test_valid_split scheduled__2023-11-09T03:02:48.569875+00:00 [running]> on host 4460f47ac51f
[2023-11-09T03:03:20.268+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Data_pipeline_dag
AIRFLOW_CTX_TASK_ID=train_test_valid_split
AIRFLOW_CTX_EXECUTION_DATE=2023-11-09T03:02:48.569875+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-09T03:02:48.569875+00:00
[2023-11-09T03:03:20.270+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/demo.py", line 24, in train_test_valid_files
    for f in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/../data/Dataset'
[2023-11-09T03:03:20.282+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=Data_pipeline_dag, task_id=train_test_valid_split, execution_date=20231109T030248, start_date=20231109T030320, end_date=20231109T030320
[2023-11-09T03:03:20.292+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 92 for task train_test_valid_split ([Errno 2] No such file or directory: '/opt/airflow/dags/../data/Dataset'; 2044)
[2023-11-09T03:03:20.335+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-11-09T03:03:20.361+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
