[2023-11-09T02:43:19.552+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Data_pipeline_dag.train_test_valid_split scheduled__2023-11-09T02:42:48.569875+00:00 [queued]>
[2023-11-09T02:43:19.560+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Data_pipeline_dag.train_test_valid_split scheduled__2023-11-09T02:42:48.569875+00:00 [queued]>
[2023-11-09T02:43:19.561+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-09T02:43:19.561+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-11-09T02:43:19.562+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-09T02:43:19.574+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): train_test_valid_split> on 2023-11-09 02:42:48.569875+00:00
[2023-11-09T02:43:19.580+0000] {standard_task_runner.py:55} INFO - Started process 678 to run task
[2023-11-09T02:43:19.584+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Data_pipeline_dag', 'train_test_valid_split', 'scheduled__2023-11-09T02:42:48.569875+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmp7lir1012']
[2023-11-09T02:43:19.587+0000] {standard_task_runner.py:83} INFO - Job 47: Subtask train_test_valid_split
[2023-11-09T02:43:19.658+0000] {task_command.py:388} INFO - Running <TaskInstance: Data_pipeline_dag.train_test_valid_split scheduled__2023-11-09T02:42:48.569875+00:00 [running]> on host 4460f47ac51f
[2023-11-09T02:43:19.726+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Data_pipeline_dag
AIRFLOW_CTX_TASK_ID=train_test_valid_split
AIRFLOW_CTX_EXECUTION_DATE=2023-11-09T02:42:48.569875+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-09T02:42:48.569875+00:00
[2023-11-09T02:43:19.728+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/demo.py", line 23, in train_test_valid_files
    for f in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/../data/Dataset'
[2023-11-09T02:43:19.740+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=Data_pipeline_dag, task_id=train_test_valid_split, execution_date=20231109T024248, start_date=20231109T024319, end_date=20231109T024319
[2023-11-09T02:43:19.749+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 47 for task train_test_valid_split ([Errno 2] No such file or directory: '/opt/airflow/dags/../data/Dataset'; 678)
[2023-11-09T02:43:19.797+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-11-09T02:43:19.822+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
