[2023-11-09T02:48:19.390+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Data_pipeline_dag.train_test_valid_split scheduled__2023-11-09T02:47:48.569875+00:00 [queued]>
[2023-11-09T02:48:19.400+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Data_pipeline_dag.train_test_valid_split scheduled__2023-11-09T02:47:48.569875+00:00 [queued]>
[2023-11-09T02:48:19.401+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-09T02:48:19.401+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-11-09T02:48:19.402+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-09T02:48:19.415+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): train_test_valid_split> on 2023-11-09 02:47:48.569875+00:00
[2023-11-09T02:48:19.421+0000] {standard_task_runner.py:55} INFO - Started process 1019 to run task
[2023-11-09T02:48:19.426+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Data_pipeline_dag', 'train_test_valid_split', 'scheduled__2023-11-09T02:47:48.569875+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmpdvebc8lx']
[2023-11-09T02:48:19.429+0000] {standard_task_runner.py:83} INFO - Job 57: Subtask train_test_valid_split
[2023-11-09T02:48:19.508+0000] {task_command.py:388} INFO - Running <TaskInstance: Data_pipeline_dag.train_test_valid_split scheduled__2023-11-09T02:47:48.569875+00:00 [running]> on host 4460f47ac51f
[2023-11-09T02:48:19.584+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Data_pipeline_dag
AIRFLOW_CTX_TASK_ID=train_test_valid_split
AIRFLOW_CTX_EXECUTION_DATE=2023-11-09T02:47:48.569875+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-09T02:47:48.569875+00:00
[2023-11-09T02:48:19.586+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/demo.py", line 23, in train_test_valid_files
    for f in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/../data/Dataset'
[2023-11-09T02:48:19.598+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=Data_pipeline_dag, task_id=train_test_valid_split, execution_date=20231109T024748, start_date=20231109T024819, end_date=20231109T024819
[2023-11-09T02:48:19.608+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 57 for task train_test_valid_split ([Errno 2] No such file or directory: '/opt/airflow/dags/../data/Dataset'; 1019)
[2023-11-09T02:48:19.642+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-11-09T02:48:19.667+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
