[2023-11-11T01:41:56.301+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: early_sepsis_prediction.load_train_test_valid_files manual__2023-11-11T01:41:54.443141+00:00 [queued]>
[2023-11-11T01:41:56.313+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: early_sepsis_prediction.load_train_test_valid_files manual__2023-11-11T01:41:54.443141+00:00 [queued]>
[2023-11-11T01:41:56.314+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-11T01:41:56.314+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-11-11T01:41:56.315+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-11T01:41:56.327+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_train_test_valid_files> on 2023-11-11 01:41:54.443141+00:00
[2023-11-11T01:41:56.336+0000] {standard_task_runner.py:55} INFO - Started process 2509 to run task
[2023-11-11T01:41:56.343+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'early_sepsis_prediction', 'load_train_test_valid_files', 'manual__2023-11-11T01:41:54.443141+00:00', '--job-id', '315', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpdfx6t9bf']
[2023-11-11T01:41:56.349+0000] {standard_task_runner.py:83} INFO - Job 315: Subtask load_train_test_valid_files
[2023-11-11T01:41:56.443+0000] {task_command.py:388} INFO - Running <TaskInstance: early_sepsis_prediction.load_train_test_valid_files manual__2023-11-11T01:41:54.443141+00:00 [running]> on host 2f30e812c633
[2023-11-11T01:41:56.549+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Pavs
AIRFLOW_CTX_DAG_ID=early_sepsis_prediction
AIRFLOW_CTX_TASK_ID=load_train_test_valid_files
AIRFLOW_CTX_EXECUTION_DATE=2023-11-11T01:41:54.443141+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-11T01:41:54.443141+00:00
[2023-11-11T01:41:57.526+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/pylab1.py", line 123, in load_train_test_valid_files
    tr_last_column = train_df.pop(train_df.columns[-1])  # Remove the last column
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4604, in __getitem__
    return getitem(key)
IndexError: index -1 is out of bounds for axis 0 with size 0
[2023-11-11T01:41:57.554+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=early_sepsis_prediction, task_id=load_train_test_valid_files, execution_date=20231111T014154, start_date=20231111T014156, end_date=20231111T014157
[2023-11-11T01:41:57.576+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 315 for task load_train_test_valid_files (index -1 is out of bounds for axis 0 with size 0; 2509)
[2023-11-11T01:41:57.629+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-11-11T01:41:57.668+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
