[2023-11-10T04:42:17.008+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: early_sepsis_prediction.feature_engineering manual__2023-11-10T04:38:38.504136+00:00 [queued]>
[2023-11-10T04:42:17.016+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: early_sepsis_prediction.feature_engineering manual__2023-11-10T04:38:38.504136+00:00 [queued]>
[2023-11-10T04:42:17.017+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-10T04:42:17.018+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-11-10T04:42:17.018+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-10T04:42:17.029+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): feature_engineering> on 2023-11-10 04:38:38.504136+00:00
[2023-11-10T04:42:17.036+0000] {standard_task_runner.py:55} INFO - Started process 6697 to run task
[2023-11-10T04:42:17.041+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'early_sepsis_prediction', 'feature_engineering', 'manual__2023-11-10T04:38:38.504136+00:00', '--job-id', '305', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp90jl621e']
[2023-11-10T04:42:17.044+0000] {standard_task_runner.py:83} INFO - Job 305: Subtask feature_engineering
[2023-11-10T04:42:17.124+0000] {task_command.py:388} INFO - Running <TaskInstance: early_sepsis_prediction.feature_engineering manual__2023-11-10T04:38:38.504136+00:00 [running]> on host 911414a99fc3
[2023-11-10T04:42:17.199+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Pavs
AIRFLOW_CTX_DAG_ID=early_sepsis_prediction
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2023-11-10T04:38:38.504136+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-10T04:38:38.504136+00:00
[2023-11-10T04:42:20.363+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/pylab1.py", line 166, in feature_engineering
    train_df = train_df.drop(train_df.columns[[8, 21, 28, 33]], axis=1)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4616, in __getitem__
    result = getitem(key)
IndexError: index 8 is out of bounds for axis 0 with size 1
[2023-11-10T04:42:20.384+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=early_sepsis_prediction, task_id=feature_engineering, execution_date=20231110T043838, start_date=20231110T044217, end_date=20231110T044220
[2023-11-10T04:42:20.399+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 305 for task feature_engineering (index 8 is out of bounds for axis 0 with size 1; 6697)
[2023-11-10T04:42:20.533+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-11-10T04:42:20.566+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
